### ISSUE TITLE
UI/UX Design

### ISSUE THREAD

**Issue by kafuikpoh** [taysek/Qwikie#5]
#### Description
User interface and experience design process

#### Tasks
- [ ] User journey maps
- [ ] Empathy maps
- [ ] Product research
- [ ] Low fidelity prototypes
- [ ] High fidelity prototypes
- [ ] Usability testing
